### ISSUE TITLE
Uninitalized constant Jekyll

### ISSUE THREAD

**Issue by waleedsarwar86** [JeroenMols/jeroenmols.github.io#1]
hi @JeroenMols i am getting following error i am trying to running `jekyll build` from Mac Terminal.

`jekyll 3.4.1 | Error:  uninitialized constant Jekyll::Paginate::Pagination::Pager
`

**Comment by JeroenMols** [comment]
Try installing an older version of jekyll: 2.4.0.
The Paginator has been removed in newer versions, breaking this Theme.
